export const SPECIAL_CONTROLLED_FRAMES = 'SPECIAL_CONTROLLED_FRAMES';
export const SPECIAL_START = 'SPECIAL_START';
export const SPECIAL_IS_LOADED = 'SPECIAL_IS_LOADED';
export const SPECIAL_END = 'SPECIAL_END';
export const SPECIAL_HOTSPOTS_LIST = 'SPECIAL_HOTSPOTS_LIST';
export const SPECIAL_CANVAS = 'SPECIAL_CANVAS';
export const SPECIAL_IMAGES_LOADED = 'SPECIAL_IMAGES_LOADED';
