pipeline:
  install:
    image: node:boron
    commands:
      - npm install
      - ./node_modules/.bin/lerna bootstrap
    when:
      event: [ push, pull_request ]

  build:
    image: node:boron
    commands:
      - ./node_modules/.bin/lerna run build
    when:
      event: [ push, pull_request ]

  test:
    image: node:boron
    commands:
      - ./node_modules/.bin/lerna run test
    when:
      event: [ push, pull_request ]

  docker_morpheus:
    image: plugins/docker
    registry: docker.soapbubble.online:5000
    repo: docker.soapbubble.online:5000/soapbubble/morpheus
    context: packages/morpheus
    dockerfile: packages/morpheus/Dockerfile
    tag: ${DRONE_COMMIT_SHA:0:7}
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  docker_auth:
    image: plugins/docker
    registry: docker.soapbubble.online:5000
    repo: docker.soapbubble.online:5000/soapbubble/auth
    context: packages/auth
    dockerfile: packages/auth/Dockerfile
    tag: ${DRONE_COMMIT_SHA:0:7}
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  docker_core:
    image: plugins/docker
    registry: docker.soapbubble.online:5000
    repo: docker.soapbubble.online:5000/soapbubble/core
    context: packages/core
    dockerfile: packages/core/Dockerfile
    tag: ${DRONE_COMMIT_SHA:0:7}
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push
