pipeline:
  install:
    image: node:boron
    commands:
      - npm install
      - ./node_modules/.bin/lerna bootstrap --loglevel silly
    when:
      event: [ push, pull_request ]


  test:
    image: node:boron
    commands:
      - npm test
    when:
      event: [ push, pull_request ]
