pipeline:
  install:
    image: node:boron
    commands:
      - npm install
      - ./node_modules/.bin/lerna bootstrap
    when:
      event: [ push, pull_request ]

  build:
    image: node:boron
    commands:
      - ./node_modules/.bin/lerna run build
    when:
      event: [ push, pull_request ]

  test:
    image: node:boron
    commands:
      - ls -la packages/morpheus/node_modules/@soapbubble/components/dist
      - cat packages/morpheus/node_modules/@soapbubble/components/package.json
    when:
      event: [ push, pull_request ]
