pipeline:
  install:
    image: node:boron
    commands:
      - npm install
      - npm run bootstrap
    when:
      event: [ push, pull_request ]

  test:
    image: node:boron
    commands:
      - ./node_modules/.bin/lerna exec --scope=@soapbubble/morpheus -- node -e "require('@soapbubble/components')"
    when:
      event: [ push, pull_request ]
