pipeline:
  install:
    image: node:boron
    commands:
      - npm install
      - npm run bootstrap
    when:
      event: [ push, pull_request ]

  test:
    image: node:boron
    commands:
      - lerna exec --scope=@soapbubble/morpheus -- npm ls @soapbubble/component
s
    when:
      event: [ push, pull_request ]
