# from https://github.com/tlackemann/nodejs-es6-ci/blob/master/.gitlab-ci.yml
# GitLab CI Docker Image
# Build - Build necessary JS files
# Deploy - Deploy application to S3/ElasticBeanstalk
stages:
  - build
# Configuration
variables:
  BUTLER_API_KEY: ""
  GOOGLE_ANALYTICS_ID: ""
  SOAPBUBBLE_CONTENTFUL_ACCESS: ""
  SOAPBUBBLE_CONTENTFUL_SPACE: ""
  SOAPBUBBLE_FB_APP_ID: ""
  DOCKER_USERNAME: "" # credentials to repo (saving to private docker registry for now)
  DOCKER_PASSWORD: "" # password for private docker repo
# Job: Install
build-morpheus:
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} docker.soapbubble.online:5000
    - docker build -t soapbubble/morpheus packages/morpheus
    - docker tag soapbubble/morpheus docker.soapbubble.online:5000/soapbubble/morpheus:latest
    - docker tag soapbubble/morpheus docker.soapbubble.online:5000/soapbubble/morpheus:${CI_COMMIT_SHA:0:7}
    - docker push docker.soapbubble.online:5000/soapbubble/morpheus:latest
    - docker push docker.soapbubble.online:5000/soapbubble/morpheus:${CI_COMMIT_SHA:0:7}
build-core:
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} docker.soapbubble.online:5000
    - docker build --build-arg GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID} --build-arg SOAPBUBBLE_CONTENTFUL_ACCESS=${SOAPBUBBLE_CONTENTFUL_ACCESS} --build-arg SOAPBUBBLE_CONTENTFUL_SPACE=${SOAPBUBBLE_CONTENTFUL_SPACE} --build-arg SOAPBUBBLE_FB_APP_ID=${SOAPBUBBLE_FB_APP_ID} -t soapbubble/core packages/core
    - docker tag soapbubble/core docker.soapbubble.online:5000/soapbubble/core:latest
    - docker tag soapbubble/core docker.soapbubble.online:5000/soapbubble/core:${CI_COMMIT_SHA:0:7}
    - docker push docker.soapbubble.online:5000/soapbubble/core:latest
    - docker push docker.soapbubble.online:5000/soapbubble/core:${CI_COMMIT_SHA:0:7}
build-auth:
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} docker.soapbubble.online:5000
    - docker build -t soapbubble/auth packages/auth
    - docker tag soapbubble/auth docker.soapbubble.online:5000/soapbubble/auth:latest
    - docker tag soapbubble/auth docker.soapbubble.online:5000/soapbubble/auth:${CI_COMMIT_SHA:0:7}
    - docker push docker.soapbubble.online:5000/soapbubble/auth:latest
    - docker push docker.soapbubble.online:5000/soapbubble/auth:${CI_COMMIT_SHA:0:7}
