# from https://github.com/tlackemann/nodejs-es6-ci/blob/master/.gitlab-ci.yml
# GitLab CI Docker Image
image: node:boron
# Build - Build necessary JS files
# Test - Run tests
# Deploy - Deploy application to S3/ElasticBeanstalk
stages:
  - install
  - test
  - build
# Configuration
variables:
  DOCKER_USERNAME: "" # credentials to repo (saving to private docker registry for now)
  DOCKER_PASSWORD: "" # password for private docker repo
# Job: Install
install:
  stage: install
  script:
    - npm install
    - ./node_modules/.bin/lerna bootstrap
  artifacts:
    untracked: true
# Job: Test
# Run tests against our application
# If this fails, we do not deploy
# test:
#   stage: test
#   dependencies:
#     - install
#   script:
#     - ./node_modules/.bin/lerna bootstrap
#     - npm test
# Jobs: Builds
build-morpheus:
  image: docker:stable
  dependencies:
    - install
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  script:
    - docker build -t docker.soapbubble.online:5000/soapbubble/morpheus packages/morpheus
    - docker tag docker.soapbubble.online:5000/soapbubble/morpheus:${CI_COMMIT_SHA:0:7} docker.soapbubble.online:5000/soapbubble/morpheus:latest
    - docker push docker.soapbubble.online:5000/soapbubble/morpheus:${CI_COMMIT_SHA:0:7} docker.soapbubble.online:5000/soapbubble/morpheus:latest

build-core:
  image: docker:stable
  dependencies:
    - install
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  script:
    - docker build -t docker.soapbubble.online:5000/soapbubble/core packages/core
    - docker tag docker.soapbubble.online:5000/soapbubble/core:${CI_COMMIT_SHA:0:7} docker.soapbubble.online:5000/soapbubble/core:latest
    - docker push docker.soapbubble.online:5000/soapbubble/core:${CI_COMMIT_SHA:0:7} docker.soapbubble.online:5000/soapbubble/core:latest

build-auth:
  image: docker:stable
  dependencies:
    - install
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  script:
    - docker build -t docker.soapbubble.online:5000/soapbubble/auth packages/auth
    - docker tag docker.soapbubble.online:5000/soapbubble/auth:${CI_COMMIT_SHA:0:7} docker.soapbubble.online:5000/soapbubble/auth:latest
    - docker push docker.soapbubble.online:5000/soapbubble/auth:${CI_COMMIT_SHA:0:7} docker.soapbubble.online:5000/soapbubble/auth:latest
