# from https://github.com/tlackemann/nodejs-es6-ci/blob/master/.gitlab-ci.yml
# GitLab CI Docker Image
# Build - Build necessary JS files
# Deploy - Deploy application to S3/ElasticBeanstalk
stages:
  - build
  - deploy
# Configuration
variables:
  BUTLER_API_KEY: ""
  CORE_GOOGLE_ANALYTICS_ID: ""
  CORE_CONTENTFUL_ACCESS: ""
  CORE_CONTENTFUL_SPACE: ""
  CORE_FB_APP_ID: ""
  BOT_TWITCH_CLIENT_ID: ""
  BOT_TWITCH_CALLBACK_URL: ""
  DOCKER_USERNAME: "" # credentials to repo (saving to private docker registry for now)
  DOCKER_PASSWORD: "" # password for private docker repo
  RANCHER_TOKEN: "" # rancher config contents
# Job: Install
build-morpheus:
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  only:
    - master
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} docker.soapbubble.online:5000
    - docker build -t soapbubble/morpheus packages/morpheus
    - docker tag soapbubble/morpheus docker.soapbubble.online:5000/soapbubble/morpheus:latest
    - docker tag soapbubble/morpheus docker.soapbubble.online:5000/soapbubble/morpheus:${CI_COMMIT_SHA:0:7}
    - docker push docker.soapbubble.online:5000/soapbubble/morpheus:latest
    - docker push docker.soapbubble.online:5000/soapbubble/morpheus:${CI_COMMIT_SHA:0:7}
build-core:
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  only:
    - master
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} docker.soapbubble.online:5000
    - docker build -t soapbubble/core --build-arg BOT_TWITCH_CLIENT_ID=${BOT_TWITCH_CLIENT_ID} --build-arg BOT_TWITCH_CLIENT_ID=${BOT_TWITCH_CLIENT_ID} --build-arg CORE_GOOGLE_ANALYTICS_ID=${CORE_GOOGLE_ANALYTICS_ID} --build-arg CORE_CONTENTFUL_ACCESS=${CORE_CONTENTFUL_ACCESS} --build-arg CORE_CONTENTFUL_SPACE=${CORE_CONTENTFUL_SPACE} --build-arg CORE_FB_APP_ID=${CORE_FB_APP_ID} packages/core
    - docker tag soapbubble/core docker.soapbubble.online:5000/soapbubble/core:latest
    - docker tag soapbubble/core docker.soapbubble.online:5000/soapbubble/core:${CI_COMMIT_SHA:0:7}
    - docker push docker.soapbubble.online:5000/soapbubble/core:latest
    - docker push docker.soapbubble.online:5000/soapbubble/core:${CI_COMMIT_SHA:0:7}
build-auth:
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  only:
    - master
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} docker.soapbubble.online:5000
    - docker build -t soapbubble/auth packages/auth
    - docker tag soapbubble/auth docker.soapbubble.online:5000/soapbubble/auth:latest
    - docker tag soapbubble/auth docker.soapbubble.online:5000/soapbubble/auth:${CI_COMMIT_SHA:0:7}
    - docker push docker.soapbubble.online:5000/soapbubble/auth:latest
    - docker push docker.soapbubble.online:5000/soapbubble/auth:${CI_COMMIT_SHA:0:7}
deploy-staging:
  image: soapbubble/rancher-cli
  stage: deploy
  tags:
    - docker
  environment:
    name: staging
    url: https://staging.soapbubble.online
  only:
    - master
  script:
    - rancher login https://rancher.soapbubble.online --token ${RANCHER_TOKEN} --context c-dpnkh:p-p9ngq
    - rancher app upgrade --values deployment/web/values-staging.yaml --set soapbubble.core.tag=${CI_COMMIT_SHA:0:7} --set soapbubble.morpheus.tag=${CI_COMMIT_SHA:0:7} --set soapbubble.auth.tag=${CI_COMMIT_SHA:0:7} web-staging deployment/web
