# from https://github.com/tlackemann/nodejs-es6-ci/blob/master/.gitlab-ci.yml
# GitLab CI Docker Image
# Build - Build necessary JS files
# Deploy - Deploy application to S3/ElasticBeanstalk
stages:
  - build
  - deploy
# Configuration
variables:
  BUTLER_API_KEY: ""
  CORE_GOOGLE_ANALYTICS_ID: ""
  CORE_CONTENTFUL_ACCESS: ""
  CORE_CONTENTFUL_SPACE: ""
  CORE_FB_APP_ID: ""
  BOT_PRODUCTION_TWITCH_CLIENT_ID: ""
  BOT_PRODUCTION_CALLBACK_URL: ""
  BOT_STAGING_TWITCH_CLIENT_ID: ""
  BOT_STAGING_CALLBACK_URL: ""
  DOCKER_USERNAME: "" # credentials to repo (saving to private docker registry for now)
  DOCKER_PASSWORD: "" # password for private docker repo
  RANCHER_TOKEN_STAGING: ""
  RANCHER_CONTEXT_STAGING: ""
  RANCHER_TOKEN_PRODUCTION: ""
  RANCHER_CONTEXT_PRODUCTION: ""
# Job: Install
build-morpheus:
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  only:
    - master
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} docker.soapbubble.online
    - docker build -t soapbubble/morpheus packages/morpheus
    - docker tag soapbubble/morpheus docker.soapbubble.online/soapbubble/morpheus:latest
    - docker tag soapbubble/morpheus docker.soapbubble.online/soapbubble/morpheus:${CI_COMMIT_SHA:0:7}
    - docker push docker.soapbubble.online/soapbubble/morpheus:latest
    - docker push docker.soapbubble.online/soapbubble/morpheus:${CI_COMMIT_SHA:0:7}
build-core:
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  only:
    - master
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} docker.soapbubble.online
    - docker build -t soapbubble/core --build-arg BOT_PRODUCTION_TWITCH_CLIENT_ID=${BOT_PRODUCTION_TWITCH_CLIENT_ID} --build-arg BOT_PRODUCTION_TWITCH_CALLBACK_URL=${BOT_PRODUCTION_TWITCH_CALLBACK_URL} --build-arg BOT_STAGING_TWITCH_CLIENT_ID=${BOT_STAGING_TWITCH_CLIENT_ID} --build-arg BOT_STAGING_TWITCH_CALLBACK_URL=${BOT_STAGING_TWITCH_CALLBACK_URL} --build-arg CORE_GOOGLE_ANALYTICS_ID=${CORE_GOOGLE_ANALYTICS_ID} --build-arg CORE_CONTENTFUL_ACCESS=${CORE_CONTENTFUL_ACCESS} --build-arg CORE_CONTENTFUL_SPACE=${CORE_CONTENTFUL_SPACE} --build-arg CORE_FB_APP_ID=${CORE_FB_APP_ID} packages/core
    - docker tag soapbubble/core docker.soapbubble.online/soapbubble/core:latest
    - docker tag soapbubble/core docker.soapbubble.online/soapbubble/core:${CI_COMMIT_SHA:0:7}
    - docker push docker.soapbubble.online/soapbubble/core:latest
    - docker push docker.soapbubble.online/soapbubble/core:${CI_COMMIT_SHA:0:7}
build-auth:
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  only:
    - master
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} docker.soapbubble.online
    - docker build -t soapbubble/auth packages/auth
    - docker tag soapbubble/auth docker.soapbubble.online/soapbubble/auth:latest
    - docker tag soapbubble/auth docker.soapbubble.online/soapbubble/auth:${CI_COMMIT_SHA:0:7}
    - docker push docker.soapbubble.online/soapbubble/auth:latest
    - docker push docker.soapbubble.online/soapbubble/auth:${CI_COMMIT_SHA:0:7}
build-proxy:
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  stage: build
  only:
    - master
  script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} docker.soapbubble.online
    - docker build -t soapbubble/proxy packages/proxy
    - docker tag soapbubble/proxy docker.soapbubble.online/soapbubble/proxy:latest
    - docker tag soapbubble/proxy docker.soapbubble.online/soapbubble/proxy:${CI_COMMIT_SHA:0:7}
    - docker push docker.soapbubble.online/soapbubble/proxy:latest
    - docker push docker.soapbubble.online/soapbubble/proxy:${CI_COMMIT_SHA:0:7}
deploy-staging:
  image: soapbubble/rancher-cli
  stage: deploy
  tags:
    - docker
  environment:
    name: staging
    url: https://staging.soapbubble.online
  when: manual
  only:
    - master
  script:
    - rancher login https://rancher.soapbubble.online --token ${RANCHER_TOKEN_STAGING} --context ${RANCHER_CONTEXT_STAGING}
    - rancher app upgrade --values deployment/web/values-staging.yaml --set soapbubble.core.tag=${CI_COMMIT_SHA:0:7} --set soapbubble.morpheus.tag=${CI_COMMIT_SHA:0:7} --set soapbubble.auth.tag=${CI_COMMIT_SHA:0:7} --set soapbubble.proxy.tag=${CI_COMMIT_SHA:0:7} web-staging deployment/web
deploy-production:
  image: soapbubble/rancher-cli
  stage: deploy
  tags:
    - docker
  environment:
    name: production
    url: https://soapbubble.online
  when: manual
  only:
    - master
  script:
    - rancher login https://rancher.soapbubble.online --token ${RANCHER_TOKEN_PRODUCTION} --context ${RANCHER_CONTEXT_PRODUCTION}
    - rancher app upgrade --values deployment/web/values-production.yaml --set soapbubble.core.tag=${CI_COMMIT_SHA:0:7} --set soapbubble.morpheus.tag=${CI_COMMIT_SHA:0:7} --set soapbubble.auth.tag=${CI_COMMIT_SHA:0:7} --set soapbubble.proxy.tag=${CI_COMMIT_SHA:0:7} web-production deployment/web
