# example
stages:
  - name: build image
    steps:
    - name: "Build"
      runScriptConfig:
        image: soapbubble/aws-cloud-build

# branch conditions for the pipeline
branch:
  include: [ twitch ]
  exclude: [ dev ]
# timeout in minutes
timeout: 30
