# example
stages:
  - name: build
    steps:
    - env:
        DEPLOYMENT: soapbubble
      runScriptConfig:
        image: "soapbubble/aws-cloud-build"
        shellScript: "bash -c \"skaffold build > deployment.yaml\""
  - name: apply
    steps:
    - applyYamlConfig:
        path: "./deployment.yaml"
# branch conditions for the pipeline
branch:
  include: [ twitch ]
  exclude: [ dev ]
# timeout in minutes
timeout: 30
