# example
stages:
  - name: build
    steps:
    - env:
        DEPLOYMENT: soapbubble
      runScriptConfig:
        image: "soapbubble/aws-cloud-build"
        shellScript: "kubectl cluster-info"
          

# branch conditions for the pipeline
branch:
  include: [ twitch ]
  exclude: [ dev ]
# timeout in minutes
timeout: 30
