# example
stages:
  - name: build image
    steps:
    - publishImageConfig:
        dockerfilePath: Dockerfile
        buildContext: packages/bot
        tag: soapbubble/bot
# branch conditions for the pipeline
branch:
  include: [ twitch ]
  exclude: [ dev ]
# timeout in minutes
timeout: 30
