# example
stages:
  - name: build image
    steps:
    - runScriptConfig:
        image: soapbubble/aws-cloud-build
        env:
          DEPLOYMENT: soapbubble
        shellScript: |
          skaffold build > deployment.yaml
    - applyYamlConfig:
        path: ./deployment.yaml
# branch conditions for the pipeline
branch:
  include: [ twitch ]
  exclude: [ dev ]
# timeout in minutes
timeout: 30
