# example
stages:

  - name: apply
    steps:
    - applyYamlConfig:
        path: "./deployment.yaml"
# branch conditions for the pipeline
branch:
  include: [ twitch ]
  exclude: [ dev ]
# timeout in minutes
timeout: 30
