apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: web
build:
  artifacts: 
    - image: null
deploy:
  kustomize:
    paths: 
      - dev.null
profiles:
  - name: local-config
    activation:
      - kubeContext: minikube
    patches:
      - op: add
        path: /deploy/kustomize/paths/-
        value: deployment/local
  - name: bot-admin-local
    activation:
      - kubeContext: minikube
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: bot-admin
          context: packages\bot-admin
  - name: bot-local
    activation:
      - kubeContext: minikube
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: bot
          context: packages\bot
  - name: cleanup
    activation:
      - kubeContext: minikube
    patches:
      - op: remove
        path: /deploy/kustomize/paths/0
      - op: remove
        path: /build/artifacts/0