export const ADD_ONMOUSEDOWN = 'INPUT_ADD_ONMOUSEDOWN';
export const ADD_ONMOUSEUP = 'INPUT_ADD_ONMOUSEUP';
export const ADD_ONMOUSEMOVE = 'INPUT_ADD_ONMOUSEMOVE';
export const ADD_ONTOUCHSTART = 'INPUT_ADD_ONTOUCHSTART';
export const ADD_ONTOUCHMOVE = 'INPUT_ADD_ONTOUCHMOVE';
export const ADD_ONTOUCHEND = 'INPUT_ADD_ONTOUCHEND';
export const ADD_ONTOUCHCANCEL = 'INPUT_ADD_ONTOUCHCANCEL';
