bot-backend:
  env:
    - name: DEPLOYMENT
      value: cluster
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/key.json
    - name: ROOT_SERVICE_ACCOUNT
      value: berglas://soapbubble-dev-secrets/google_application_credentials
    - name: BOT_PROFILE_ID
      value: berglas://soapbubble-dev-secrets/twitch_profile_id
    - name: BOT_DISCORD_TOKEN
      value: berglas://soapbubble-dev-secrets/discord_token
    - name: BOT_TWITCH_CLIENT_ID
      value: berglas://soapbubble-dev-secrets/twitch_client
    - name: BOT_TWITCH_CLIENT_SECRET
      value: berglas://soapbubble-dev-secrets/twitch_client_secret
    - name: BOT_TWITCH_SECRET
      value: berglas://soapbubble-dev-secrets/twitch_secret
  webhook: https://twitch.soapbubble.online/bot/api/hook
  saveChannelNames:
    - captemulation
    - chocotaco
    - shroud
    - day9tv
    - glermz
    - halifax
  image:
    repository: us.gcr.io/soapbubble-dev/bot-backend
  imagePullSecrets:
    - name: "soapbubble-dev"
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      rancher.io/globalDNS.hostname: "twitch.soapbubble.online"
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.org/websocket-services: "bot-backend"
    hosts:
      - host: twitch.soapbubble.online
        paths:
          - "/api"
          - "/socket.io"
    tls:
      - secretName: twitch-tls
        hosts:
          - twitch.soapbubble.online
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi

  volumeMounts:
    - name: gcp-serviceaccount
      mountPath: "/secret"
      readOnly: true
  volumes:
    - name: gcp-serviceaccount
      secret:
        secretName: gcp-serviceaccount

bot-webapp:
  redirect: https://twitch.soapbubble.online/api/twitchCallback
  image:
    repository: us.gcr.io/soapbubble-dev/bot-webapp
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secret/key.json
    - name: ROOT_SERVICE_ACCOUNT
      value: berglas://soapbubble-dev-secrets/google_application_credentials
    - name: BOT_ADMIN_SOCKETIO
      value: ws://twitch.soapbubble.online/bot/
    - name: BOT_ADMIN_TWITCH_CLIENT_ID
      value: berglas://soapbubble-dev-secrets/twitch_client
    - name: BOT_ADMIN_TWITCH_SECRET
      value: berglas://soapbubble-dev-secrets/twitch_client_secret
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512i
  imagePullSecrets:
    - name: "soapbubble-dev"
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      rancher.io/globalDNS.hostname: "twitch.soapbubble.online"
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: twitch.soapbubble.online
        paths:
          - "/"
    tls:
      - secretName: twitch-tls
        hosts:
          - twitch.soapbubble.online
  volumeMounts:
    - name: gcp-serviceaccount
      mountPath: "/secret"
      readOnly: true
  volumes:
    - name: gcp-serviceaccount
      secret:
        secretName: gcp-serviceaccount
