export const DIMENSIONS_RESIZE = 'GAME_DIMENSIONS_RESIZE';
export const GAME_SCENE_LOADING = 'GAME_SCENE_LOADING';
export const GAME_SET_VOLUME = 'GAME_SET_VOLUME';
export const GAME_SET_CURSOR = 'GAME_SET_CURSOR';
export const CREATE_CANVAS = 'GAME_CREATE_CANVAS';
