apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "berglas-mutatingwebhook.fullname" . }}-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "berglas-mutatingwebhook.fullname" . }}
spec:
  secretName: {{ include "berglas-mutatingwebhook.fullname" . }}-certificate
  dnsNames:
    - {{ include "berglas-mutatingwebhook.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "berglas-mutatingwebhook.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "berglas-mutatingwebhook.fullname" . }}.{{ .Release.Namespace }}.svc.cluster
    - {{ include "berglas-mutatingwebhook.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ include "berglas-mutatingwebhook.fullname" . }}-selfsigned
