apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
        - name: www
          image: www
          env:
            - name: PORT
              value: '3080'
          ports:
            - containerPort: 3080
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: www
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: www
  minReplicas: 2
  maxReplicas: 9
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: www
  name: www
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 3080
      protocol: TCP
      targetPort: 3080
  selector:
    app: www
  sessionAffinity: None
  type: NodePort
