apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
        - name: www
          image: www
          env:
            - name: PORT
              value: '3080'
          ports:
            - containerPort: 3080
          # Resource requests are tuned for early SSR app. Will need to migrate
          # to service mesh or bump these values up as the service grows
          resources:
            requests:
              memory: '250Mi'
              cpu: '50m'
            limits:
              memory: '250Mi'
              cpu: '50m'
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: www
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: www
  minReplicas: 2
  maxReplicas: 30
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: www
  name: www
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 443
      protocol: TCP
      targetPort: 3080
  selector:
    app: www
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: www
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: sandboxvr-ssl
spec:
  backend:
    serviceName: www
    servicePort: 443
