# Default values for web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

pullPolicy: IfNotPresent

configMap: soapbubble-web
secrets: soapbubble-web

soapbubble:
  core:
    image: docker.soapbubble.online:5000/soapbubble/core
    tag: latest
    env:
    - name: CORE_PORT
      value: "80"
  auth:
    image: docker.soapbubble.online:5000/soapbubble/auth
    tag: latest
    env:
    - name: AUTH_PORT
      value: "80"
    - name: AUTH_ROOT_PATH
      value: "/auth"
  morpheus:
    image: docker.soapbubble.online:5000/soapbubble/morpheus
    tag: latest
    env:
    - name: MORPHEUS_PORT
      value: "80"
    - name: MORPHEUS_PRIME_DB
      value: "true"
    - name: MORPHEUS_UPDATE_DB
      value: "true"

imagePullSecrets:
  - name: soapbubble
nameOverride: ""
fullnameOverride: ""

letsencrypt:
  enabled: true
  # Resource name of the letsencrypt cert
  certificate: soapbubble-online-crt
  # Where the cert secret is stored (should match ingress.tls[].secretName)
  tlsSecretName: soapbubble-online-tls
  # Host for the cert (should match ingress.tls[].hosts[0])
  host: soapbubble.online

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  tls: true
  host: soapbubble.online
  secretName: soapbubble-online-tls

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

mongodb:
  enabled: true
  replicaSet:
    enabled: true
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
