# Staging values

pullPolicy: Always

soapbubble:
  core:
    env:
      CORE_ENVIRONMENT: staging
  morpheus:
    env:
      MORPHEUS_ENVIRONMENT: staging

configMap: soapbubble-staging-web
secrets: soapbubble-staging-web

ingress:
  host: staging.soapbubble.online
  secretName: staging-soapbubble-online-tls

requirements:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi
