apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-admin
spec:
  template:
    spec:
      containers:
      - name: bot-admin
        image: soapbubble/bot-admin
        env:
        - name: BOT_ADMIN_SOCKETIO
          value: ws://192.168.99.101/bot/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  template:
    spec:
      containers:
      - name: bot
        image: soapbubble/bot
  