
export const BOT_FETCH = 'ADMIN_BOT_FETCH';
export const BOT_FETCH_SUCCESS = 'ADMIN_BOT_FETCH_SUCCESS';
export const BOT_FETCH_FAILURE = 'ADMIN_BOT_FETCH_FAILURE';
export const BOT_LETSPLAY = 'ADMIN_BOT_LETSPLAY';
export const BOT_SETTINGS_INPUT = 'ADMIN_BOT_SETTINGS_INPUT';
export const BOT_SETTINGS_CANCEL = 'ADMIN_BOT_SETTINGS_CANCEL';
export const BOT_SETTINGS_SUBMIT = 'ADMIN_BOT_SETTINGS_SUBMIT';
export const BOT_RESTART = 'ADMIN_BOT_RESTART';
