export const VIDEO_LOAD_START = 'VIDEO_LOAD_START';
export const VIDEO_LOAD_COMPLETE = 'VIDEO_LOAD_COMPLETE';
export const VIDEO_IS_PLAYING = 'VIDEO_IS_PLAYING';
export const VIDEO_PLAY_DONE = 'VIDEO_PLAY_DONE';
