export default {
  casts: [
    {
      castId: 0,
      comparators: [],
      cursorShapeWhenActive: 10000,
      defaultPass: false,
      gesture: 2,
      initiallyEnabled: true,
      param1: 2000,
      param2: 0,
      param3: 0,
      rectBottom: 400,
      rectLeft: 0,
      rectRight: 640,
      rectTop: 0,
      type: 0,
    },
    {
      angleAtEnd: -1,
      castId: 99,
      comparators: [],
      dissolveToNextScene: false,
      endFrame: -1,
      fileName: 'GameDB/OAsounds/claireSRMSC',
      initiallyEnabled: true,
      location: {
        x: 0,
        y: 0,
      },
      looping: true,
      startFrame: 0,
      audioOnly: true,
    },
  ],
  sceneId: 1,
  sceneType: 8,
};
