export const SCENE_CANVAS_CREATED = 'SCENE_CANVAS_CREATED';
export const SCENE_LOAD_START = 'SCENE_LOAD_START';
export const SCENE_LOAD_COMPLETE = 'SCENE_LOAD_COMPLETE';
export const SCENE_CREATE_3D = 'SCENE_CREATE_3D';
