version: '2'
services:
  elasticsearch:
    scale: 1
    start_on_create: true
  web:
    scale: 1
    start_on_create: true
  data-volume:
    scale: 1
    start_on_create: true
  kibana:
    scale: 1
    start_on_create: true
  fluentd:
    scale: 1
    start_on_create: true
