export const SCENE_SET_BACKGROUND_SCENE = 'SCENE_SET_BACKGROUND_SCENE';
export const SCENE_SET_CURRENT_SCENE = 'SCENE_SET_CURRENT_SCENE';
export const SCENE_DO_ENTERING = 'SCENE_DO_ENTERING';
export const SCENE_DO_ENTER = 'SCENE_DO_ENTER';
export const SCENE_DO_EXITING = 'SCENE_DO_EXITING';
export const SCENE_DO_ACTION = 'SCENE_DO_ACTION';

export const SCENE_LOAD_START = 'SCENE_LOAD_START';
export const SCENE_LOAD_COMPLETE = 'SCENE_LOAD_COMPLETE';
export const SCENE_DISPLAY_PANORAMA = 'SCENE_DISPLAY_PANORAMA';
export const SCENE_DISPLAY_TRANSITION = 'SCENE_DISPLAY_TRANSITION';
export const SCENE_END = 'SCENE_END';
