apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: bot
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /opt/secrets/service-account.json
            - name: BOT_ORIGIN
              value: '*'
            - name: BOT_PROFILE_ID
              valueFrom:
                configMapKeyRef:
                  key: BOT_PROFILE_ID
                  name: bot-secrets
            - name: BOT_DISCORD_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: token
                  name: discord-secrets
            - name: BOT_TWITCH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: client
                  name: twitch-secrets
            - name: BOT_TWITCH_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: secret
                  name: twitch-secrets
            - name: BOT_TWITCH_WEBHOOK
              valueFrom:
                configMapKeyRef:
                  key: BOT_TWITCH_WEBHOOK
                  name: bot-secrets
            - name: BOT_TWITCH_SECRET
              valueFrom:
                configMapKeyRef:
                  key: secret
                  name: twitch-secrets
            - name: BOT_PORT
              value: '80'
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /opt/secrets
              name: secrets
      volumes:
        - name: secrets
          secret:
            items:
              - key: service.json
                path: service-account.json
            secretName: google-secrets
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bot
  name: bot
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: bot
  type: NodePort
