apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: bot
          env:
            - name: BOT_PORT
              value: '80'
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '800Mi'
              cpu: '250m'
            limits:
              memory: '800Mi'
              cpu: '250m'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bot
  name: bot
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: bot
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bot
spec:
  backend:
    serviceName: bot
    servicePort: 80
